### ISSUE TITLE
Test that survival metrics can handle case weights

### ISSUE THREAD

**Issue by hfrick** [tidymodels/extratests#112]
Is this already covered in yardstick?

**Comment by EmilHvitfeldt** [comment]
it sure it

- https://github.com/tidymodels/yardstick/blob/main/tests/testthat/test-surv-brier_survival.R#L16
- https://github.com/tidymodels/yardstick/blob/main/tests/testthat/test-surv-brier_survival_integrated.R#L25
- https://github.com/tidymodels/yardstick/blob/main/tests/testthat/test-surv-concordance_survival.R#L12

**Comment by EmilHvitfeldt** [comment]
And I would argue that it should keep them there, as we already test for case weights of the other metrics in yardstick

**Comment by hfrick** [comment]
Awesome! Do you think we should add anything to this? If not, please do the honors of closing this issue!

**Comment by EmilHvitfeldt** [comment]
I think we are good on this front! as in, we are testing the case weights use cases in survival metrics to the same standard as the other metrics!
