### ISSUE TITLE
Add test on logging for racing with survival models

### ISSUE THREAD

**Issue by hfrick** [tidymodels/extratests#138]
The issue mentioned in this comment has been closed https://github.com/tidymodels/finetune/issues/81

https://github.com/tidymodels/extratests/blob/15314420e460a9e05ce81a74cfd411bf482c6fde/tests/testthat/test-survival-tune-race.R#L404-L406

**Comment by topepo** [comment]
Closed by #158

Specifically [these lines](https://github.com/tidymodels/extratests/blob/683ec31268d2af45634ea9779835ee0fa09e7ba6/tests/testthat/test-survival-tune_race_anova.R#L279-L301)

**Comment by hfrick** [comment]
I read that code comment as "check that the evaluation time is mentioned" whereas the test checks that the metric is mentioned. Shall we reopen this issue or is that a misunderstanding?

**Comment by hfrick** [comment]
Keeping this closed, Max produced this as a receipt 😛  https://github.com/tidymodels/extratests/blob/683ec31268d2af45634ea9779835ee0fa09e7ba6/tests/testthat/test-survival-tune_race_anova.R#L440
