### ISSUE TITLE
Test `int_pctl()` for survival models

### ISSUE THREAD

**Issue by hfrick** [tidymodels/extratests#163]

**Comment by simonpcouch** [comment]
Just to make sure I have the right background here—I should pick up from https://github.com/tidymodels/extratests/commit/c2ff585052ffe88288478d0cfa699c5740c58e1f and get that polished enough to merge, holding off on tests for tidymodels/tune#809 until that's been addressed?

**Comment by topepo** [comment]
I'm going to make an argument _against_ tidymodels/tune#809 so I would look at this as-is.

Also the tune PR is now merged so I restarted CI in #180

**Comment by topepo** [comment]
Closed by #180
