### ISSUE TITLE
GHA failures due to aorsf archival

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/extratests#171]
GH R-CMD-CHECK is [failing](https://github.com/tidymodels/extratests/actions/runs/7572208193/job/20624868414?pr=166) with:

```
  Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * deps::.: Can't install dependency aorsf
  * aorsf: Can't find package called aorsf.
  * any::sessioninfo: dependency conflict
  * any::rcmdcheck: dependency conflict
```

as aorsf got booted from CRAN. Let's configure so we install from GitHub for now.

**Comment by hfrick** [comment]
todo: add remote to censored

**Comment by simonpcouch** [comment]
For whatever reason, pak [still trips up](https://github.com/tidymodels/extratests/actions/runs/7572823592/job/20629666186?pr=169) on that Remote after merge of tidymodels/censored#299. Will try adding a Remote to extratest's DESCRIPTION.
